---
micronaut:
  application:
    name: test-app
jackson:
  module-scan: false
---
micronaut:
  server:
    port: 8123
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
          - "http://localhost:3000"
  security:
    enabled: false
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATUzRE_SECRET:pleaseChangeThisSecretForANewOne}"
bearer:
  public: publicToken
